server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/college_db
    username: root
    password: Shree@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc.http.methods.patch.enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info